#!/bin/bash

docker run --volume $(pwd):/home/cross/project \
  --volume $HOME/.cargo/registry:/home/cross/.cargo/registry rust-stable-pi-cross:latest \
  build --release --color=always && \
    scp target/arm-unknown-linux-gnueabihf/release/frame-decode pi@milkbar.local:~/ && \
    ssh pi@milkbar.local -t "sudo ./frame-decode"
